version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.14
    steps:
      - run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0
      - checkout
      - run: golangci-lint run
      - run: go test -v -coverprofile=coverage.txt -covermode=atomic ./...
      - run: bash <(curl -s https://codecov.io/bash)
