version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.14
    steps:
      - checkout
      - run: go vet ./...
      - run: go test -v -coverprofile=coverage.txt -covermode=atomic ./...
      - run: bash <(curl -s https://codecov.io/bash)
